Django_GestionesCasasVersion1_11/Django_GestionesCasasVersion1_11/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import settings
from . import views


urlpatterns = [
    url(r'^login/$', views.login_page, name='login'),
    url(r'^login/savechat/$', views.save_chat, name='xat'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^search/$', views.search, name='search'),
    url(r'^calendar/', include('calendarium.urls')),
    #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
     #   'document_root': settings.MEDIA_ROOT
	
    #}), 
]

Django_GestionesCasasVersion1_11/polls/urls.py
from django.conf.urls import url

from . import views
#from . import month_cal

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    #url(r'^$', views.index, name='index'),
    url(r'^cases/$', views.CasesView.as_view(), name='cases'),
    # ex: /polls/5/
    #the 'name' value as called by the {% url %} template tag
    #url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^cases/(?P<cases_id>[0-9]+)/persona$', views.casesDetail, name='detail'),
    url(r'^persona/(?P<persona_id>[0-9]+)/factura$', views.factura, name='detail_persona'),
    url(r'^factura/(?P<persona_id>[0-9]+)/insercio$', views.save_factura, name='factura_nova'),
    url(r'^nota/(?P<persona_id>[0-9]+)/insercio$', views.anade_nota, name='insercio_nota'),
    #url(r'^cases/(?P<pk>[0-9]+/))
    # added the word 'specifics'
    #url(r'^specifics/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    #url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    #url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    #url(r'^(?P<cases_id>[0-9]+)/vote/$', views.vote, name='vote'),
    #url(r'^calendar/$', views.CalendarView.as_view(), name='calendar')
    url(r'^users/$', views.UsersView.as_view(), name='users'),
    #url(r'^xat/$', views.XatView.as_view(), name='xat'),
    url(r'^xat/$', views.xat, name='xat'),
    url(r'^users/(?P<pk>[0-9]+)/user_detail/$', views.UserDetailView.as_view(), name='user_detail'),
    #url(r'^nota/$', views.NotaView.as_view(), name='nota'),
    
    url(r'^calendario2/$', views.calendar2, name='calendar2'),
    url(r'^calendario/$', views.calendario, name='calendar'),
    #url(r'^calendar_month/$', views.calendar_month, name='calendar_month'),
    #url(r'^calendar_month/(?P<year>[0-9]{4})/(?P<month>[01]*[0-9]+)/$', views.calendar_month_day, name='calendar_month_day'),
    url(r'^xats/(?P<year>\d{4})/$', views.xatsEnguany, name='xatsEnguany'),
    url(r'^xats/(?P<year>[0-9]{4})/(?P<month>[01]*[0-9]+)/$', views.xatsEnguanyMes, name='xatsEnguanyMes'),
    #url(r'^blog/(?P<year>\d{4})/(?P<month>[01]*[0-9]+)/(?P<day>[0-3]*[0-9]+)$',views.EntradasDia.as_view(), name='entradas'),
    #url(r'^blog/(?P<year>\d{4})/(?P<month>[01]*[0-9]+)/$',views.EntradasMes.as_view(), name='entradas'),
    #url(r'^blog/(?P<year>\d{4})/$',
    #views.EntradasYear.as_view(), name='entradas_year'),
    #url(r'^blog/(?P<year>\d{4})/$',
    #views.year, name='entradas_year'),
    #url(r'^blog/$', views.BlogView.as_view(), name='blog'),
    url(r'^persona/(?P<persona_id>[0-9]+)/blog/$', views.blog, name='blog'),
    url(r'^iframe/$', views.iframe, name='iframe'),
    url(r'^persona/(?P<persona_id>[0-9]+)/btc_address/$', views.btc_address, name='bit_address'),

]

Django_GestionesCasasVersion1_11/polls/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Cases(models.Model):
    localitat = models.CharField(max_length=200)
    adressa = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.localitat

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Persona(models.Model):
    cognoms = models.CharField(max_length=200)
    nom = models.CharField(max_length=200)
    email = models.EmailField()
    btc_address = models.CharField(max_length=34, null=True)
    id_casa = models.ForeignKey(Cases, on_delete=models.CASCADE)
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.nom

"""
class Login(models.Model):
    usuari = models.CharField(max_length=100)
    contrassenya = models.CharField(max_length=100)
    id_persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    def __str__(self):
        return self.usuari
"""

class Xat(models.Model):
    date_sent = models.DateTimeField(auto_now_add=True)
    #user = models.CharField(max_length=100)
    user = models.ForeignKey(User)
    text = models.CharField(max_length=100)
    #id_usuari = models.ForeignKey(Login, on_delete=models.CASCADE)
    def __str__(self):
        return self.text

class NotaCalendario(models.Model):
    dateField = models.DateField(auto_now_add=True)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    nota = models.CharField(max_length=2000)

    def __str__(self):
        return self.nota

class Factura(models.Model):
    pub_date = models.DateField(auto_now_add=True)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    image = models.ImageField()
    preu = models.FloatField()
    def __str__(self):
        return str(self.preu)

Django_GestionesCasasVersion1_11/polls/forms.py
from django import forms
#from django import ModelForm
from .models import Factura, NotaCalendario

"""class ContactoForm(forms.Form):
		correo = forms.EmailField(label='Tu correo electronico')
		mensaje = forms.CharField(widget=forms.TextArea)

"""
"""class Accede(ModelForm):
	class Meta:
		Model = Login
		usuario = forms.CharField(label='Usuario: ',max_length=100, required=True)
		contrassenya = forms.CharField(max_length=100, required=True)"""
"""class LoginForm(forms.LoginForm):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput())"""

class ChatForm(forms.Form):
	escriu = forms.CharField(max_length=100,required=True)

class FacturaForm(forms.ModelForm):

    class Meta:
        model = Factura
        fields = ['persona', 'image', 'preu']

class AnadeNotaForm(forms.ModelForm):
	class Meta:
		model = NotaCalendario
		fields = ['nota', 'persona']

Django_GestionesCasasVersion1_11/polls/views.py
# -*- coding: utf-8 -*-
from django.http import Http404
from django.shortcuts import get_object_or_404, render, render_to_response, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import loader, RequestContext
from django.views import generic
from django.utils import timezone
from .forms import ChatForm, FacturaForm, AnadeNotaForm
from datetime import datetime, date, time, timedelta
from .models import Cases, Persona, Xat, NotaCalendario
from django.contrib.auth.models import User
import calendar
# Create your views here.

def calendar2(request):
    year = date.today().year 
    month = date.today().month
    day = date.today().day
    cad = "{0}-{1}-{2}".format(year,month,day)
    return HttpResponse(cad)

def calendario(request):
    year = date.today().year 
    month = date.today().month
    day = date.today().day
    calendario_mes = calendar.month(year, month)
    return HttpResponse(calendario_mes)
"""
class EntradasDia(generic.DayArchiveView):
    queryset=NotaCalendario.objects.order_by('dateField')
    template_name='polls/entradas_dia.html'
    date_field = 'dateField'
    context_object_name='entradas'
    month_format = '%m'

class EntradasMes(generic.MonthArchiveView):
        '''Entradas por mes'''
        queryset=NotaCalendario.objects.order_by('dateField')
        template_name='polls/entradas_mes.html'
        date_field = 'dateField'
        month_format = '%m'
        context_object_name='entradas'

class  EntradasYear(generic.YearArchiveView):
        '''Entradas por año'''
        queryset=NotaCalendario.objects.order_by('dateField')
        template_name='polls/entradas_anyo.html'
        date_field = 'dateField'
        context_object_name='entradas'
        make_object_list='True'
"""
class BlogView(generic.ListView):
    template_name = 'polls/blog.html'
    context_object_name = 'entradas_list'
    def get_queryset(self):
        """
        Return the last five published questions (not including     those set to be
        published in the future).
        """
        return NotaCalendario.objects.filter(
        dateField__lte=timezone.now()
        ).order_by('-dateField')[:5]

def blog(request, persona_id):
    model = Persona
    persona = Persona.objects.get(pk=persona_id)
    year = date.today().year
    month = date.today().month
    day = date.today().day
    context = {'persona': persona, 'year':year, 'month':month, 'day':day}
    return render(request, 'polls/blog.html', context)
def btc_address(request, persona_id):
    model = Persona
    persona = Persona.objects.get(pk=persona_id)
    context = {'persona': persona}
    return render(request, 'polls/btc_address.html', context)
    
class CasesView(generic.ListView):
    template_name = 'polls/cases.html'
    context_object_name = 'latest_cases_list'
    def get_queryset(self):

        return Cases.objects.filter(
        pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class UsersView(generic.ListView):
    template_name = 'polls/users.html'
    context_object_name = 'latest_users_list'
    
    def get_queryset(self):
        """
        Return the last five published questions (not including     those set to be
        published in the future)."""
        return User.objects.all()
"""
class XatView(generic.ListView):
    template_name = 'polls/xat.html'
    context_object_name = 'xat_list'
    
    def get_queryset(self):
        """"""
        Return the last five published questions (not including     those set to be
        published in the future).
        """"""
        return Xat.objects.all()"""

def xat(request):
    xats = Xat.objects.order_by('-date_sent')[:5]
    year=date.today().year
    month = date.today().month
    if request.method == 'POST':
        form = ChatForm(request.POST)
        if form.is_valid():
            escriu = request.POST['escriu']
            xat = Xat.objects.create(text=escriu, user=request.user)
            xat.save()
    else:
        form = ChatForm()
    context = {'xats': xats, 'year':year, 'month':month, 'form':form}
    return render(request, 'polls/xat.html', context)
"""class XatDetailView(generic.DetailView):
    model = Xat
    template_name = 'polls/xat_detail.html'
    def get_queryset(self):
        """"""
        Excludes any questions that aren't published yet.
        """"""
        return Xat.objects.all()
"""
class NotaView(generic.ListView):
    template_name = 'polls/enguany.html'
    context_object_name = 'nota_list'
    def get_queryset(self):
        """
        Return the last five published questions (not including     those set to be
        published in the future).
        """
        current_year = timezone.now().year
        return NotaCalendario.objects.filter(dateField__year = current_year)



class UserDetailView(generic.DetailView):
    model = User
    template_name = 'polls/user_detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return User.objects.all()

def casesDetail(request, cases_id):
    model = Cases
    template_name = 'polls/detail.html'
    cases = Cases.objects.get(pk=cases_id)
    context = {'cases':cases}
    return render(request, template_name, context)

def factura(request, persona_id):
    model = Persona
    template_name = 'polls/detail_persona.html'
    persones = Persona.objects.get(pk=persona_id)
    message = ""
    context = {'persones':persones}
    return render(request, template_name, context)

def save_factura(request, persona_id):
    message = ""
    if request.method == 'POST':
        form = FacturaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            message = "Image uploaded succesfully!"   
        else:
            message = "Errada en la pujada de l'imatge"   
    else:
        form = FacturaForm()
    persona = Persona.objects.get(pk=persona_id)
    return render(request, 'polls/factura_nova.html', {'form':form, 'message':message, 'persona':persona})

def anade_nota(request, persona_id):
    persona = Persona.objects.get(pk=persona_id)
    message = ""
    if request.method == 'POST':
        form = AnadeNotaForm(request.POST)
        if form.is_valid():
            form.save()   
            message = "Nota enviada correctament"
        else:
            message = "Errada"
    else:
        form = AnadeNotaForm()
    return render(request, 'polls/nota_nova.html', {'form':form, 'persona':persona, 'message':message})

def vote(request, cases_id):
    cases = get_object_or_404(Cases, pk=cases_id)
    try:
        selected_persona = cases.persona_set.get(pk=request.POST['persona'])
    except (KeyError, Persona.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'cases': cases,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_persona.votes += 1
        selected_persona.save()

def xatsEnguany(request, year):
    try:
        year = date.today().year
        xats = Xat.objects.filter(date_sent__year=year)
    except Xat.DoesNotExist:
        raise Http404("Xat does not exist")
    return render(request, 'polls/enguany.html', {'year':year, 'xats': xats})

def calendar_month(request):
    try:
        now = timezone.now()
        xat = Xat.objects.filter(date_sent__month=now.month, date_sent__year=now.year)
    except NotaCalendario.DoesNotExist:
        raise Http404("Nota does not exist")
    return redirect('polls:calendar_month_day')

def xatsEnguanyMes(request, year, month):
    try:
        year = datetime.today().year
        month = datetime.today().month
        xats = Xat.objects.filter(date_sent__year=year, date_sent__month=month)
    except NotaCalendario.DoesNotExist:
        raise Http404("Nota does not exist")
    return render(request, 'polls/enguanymes.html', {'year':year, 'month': month, 'xats': xats})

def year(request, year):
    try:
        now = timezone.now()
        entradas_list = NotaCalendario.objects.filter(dateField__year=year)
    except NotaCalendario.DoesNotExist:
        raise Http404("Nota does not exist")
    return render(request, 'polls/entradas_anyo.html', {'year':now.year, 'entradas_list': entradas_list})
    
def iframe(request):
    try:
        year = datetime.today().year
        month = datetime.today().month
        xats = Xat.objects.filter(date_sent__year=year)
    except NotaCalendario.DoesNotExist:
        raise Http404("Xat does not exist")
    return render(request, 'polls/iframe.html', {'year':year, 'month':month, 'xats': xats})

def save_chat(request):
    #Xat.objects.create()
    # usuario: request.user
    # texto
    # - fecha
    if request.method == 'POST':
        form = ChatForm(request.POST)
        if form.is_valid():
            escriu = request.POST['escriu']
            xat = Xat.objects.create(text=escriu, user=request.user)
            xat.save()
            
    return redirect('polls:xat')

Django_GestionesCasasVersion1_11/polls/templates/polls/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ca">
<head>
	<title>{% block title %} {% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
</head>
<body>
	<div id="wrapper">
	{% if user.is_authenticated %}
		<a href="{% url 'polls:user_detail' user.id %}">{{ user.username }}</a>&nbsp|&nbsp
		<a href="{% url 'logout' %}">surt</a>
	{% endif %}
	<h1>{% block h1 %}Entropy {% endblock %}</h1>
	<nav>
		<a href="{% url 'polls:cases' %}">Cases</a>&nbsp|&nbsp
		{% if user.is_authenticated %}
		<a href="{% url 'polls:xat' %}">Xats</a>&nbsp|&nbsp

			<a href="{% url 'polls:users' %}">Contactes</a>&nbsp|&nbsp
			<a href="/calendar">Calendari</a>
		{% else %}
			<a href="{% url 'login' %}">Login</a>&nbsp
			|&nbsp
		{% endif %}
		
			
		
	</nav>
	<section>
		{% block content %}{% endblock %}
	</section>
	<aside>
			{% block aside %} {% endblock %} 
		
	</aside>
</div>
</body>
<nav id="navinf">{% block navinf %}{% endblock %}</nav>
<footer>
	<address>Entropy Factory S.L. &copy; 2016 Les Coves de Vinrom&agrave;</address>
</footer>
</html>

Django_GestionesCasasVersion1_11/polls/templates/polls/blog.html
{% extends 'polls/base.html' %}
{% block title %}Bienvenidos a MiBlog {% endblock %}
{{year}}
{% block content %}
<a href="/polls/persona/{{persona.id}}/factura">Factures</a>&nbsp|&nbsp
<a href="/polls/persona/{{persona.id}}/blog">Notes</a>&nbsp|&nbsp
<a href="/polls/persona/{{persona.id}}/btc_address">Adreça bitcoin</a>
<h2>{{persona.nom}}</h2>
{% for nota in persona.notacalendario_set.all %}
  {% if nota %}
<ul>
  <h3>[{{nota.dateField}}]</h3>
    <ul><li>{{nota.nota}}</li></ul>
</ul>
{% else %}
   <p>
        No hay Entradas.
   </p>
{% endif %} 
{% endfor %}
{% endblock %}
{% block aside %}
  <a href="/polls/nota/{{persona.id}}/insercio">Afegir nota </a>
  
{% endblock %}

Django_GestionesCasasVersion1_11/polls/templates/polls/cal_mes.html
{% load cal_mes %}
{% cal_mes %}
<table class="cal_month_calendar">
<tr>
    {% for day in headers %}
    <th>{{ day|date:"D"|slice:":3" }}</hd>
{% endfor %}
</tr>
    {% for week in calendar %}
    <tr>
{% for day in week %}
    <td{% if not day.in_month %} class="cal_not_in_month"{% endif %}>{% if day.event %}<a href="/polls/{{ day.day|date:"Y/m/d" }}">{{ day.day|date:"j" }}</a>{% else %}{{ day.day|date:"j" }}{% endif %}</td>
{% endfor %}
    </tr>
{% endfor %}
    </table>

Django_GestionesCasasVersion1_11/polls/templates/polls/cases.html
{% extends "polls/base.html" %}

{% block title %}Index{% endblock %}
{% block h1 %} Cases d'Entropy {% endblock %}

{% block content %}
<div id="cases">		
		{% if latest_cases_list %}

			<ul>
			{% for cases in latest_cases_list %}
				<li><a href="{% url 'polls:detail' cases.id %}"> {{ cases.localitat }} </a>
				 <span class="negreta">&nbsp;&nbsp;Direcci&oacute;: {{ cases.adressa }} </span>
				 &nbsp;&nbsp;<span class="cursiva">Creat el {{ cases.pub_date }}<span></li>
			{% endfor %}
			</ul>
		{% else %}
			<p>No polls are available.</p>
		{% endif %}
</div>		
{% endblock %}


			

Django_GestionesCasasVersion1_11/polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
{% block title %}Persones{% endblock %}
{% block content %}

<h1> Persones que viuen en {{ cases.localitat }} </h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}



{% for persona in cases.persona_set.all %}
    
    	 <li><span class="negreta"><a href="/polls/persona/{{persona.id}}/blog" title="blog">{{ persona.nom }} {{ persona.cognoms }} </span></a>{{persona.btc_address}}</li> <br>
    
{% endfor %}
{% if latest_users_list %}
		{% for users in latest_users_list %}
    		<span class="negreta"></div>-{{ users.username }} {{ users.username }}</a></span> <br>
    	{% endfor %}
	{% endif %}	


{% endblock %}

Django_GestionesCasasVersion1_11/polls/templates/polls/enguany.html
{% extends "polls/base.html" %}
{% block title %} Xats {{ year }} {% endblock %}
{% block content %}
<h1>Xats d'enguany {{ year }}</h1>
{% if xats %} 
	{% for xat in xats %}
		[{{ xat.date_sent }}] {{ xat.user }}: {{ xat.text }}  <br>
	{% endfor %}
{% endif %}
{% endblock %}

Django_GestionesCasasVersion1_11/polls/templates/polls/entradas_dia.html
{% extends 'polls/base.html' %}
{% block title %}miblog|{{ day|date }}{% endblock %}

{% block content %}
    <h3> Entradas del día:

{% for entrada in entradas %}

    {% ifchanged %}{{entrada.dateField|date:"d  M  Y"}}</h3>{% endifchanged %}
    <ul>
    <li> {{ forloop.counter }} {{entrada.user}}: <a href="{{entrada.get_absolute_url }}">{{ entrada }}</a></li></ul>
    {% endfor %}
    

{% endblock %}

Django_GestionesCasasVersion1_11/polls/templates/polls/entradas_mes.html
{% extends 'polls/base.html' %}
{% block title %}miblog|{{ month|date:"F" }}{% endblock %}

{% block content %}
    <h2>  Entradas del Mes de {{ month|date:"F" }} <h2>
{% for entrada in entradas %}

    {% ifchanged %} <h3> {{entrada.fecha|date:"Y/m/d"}}</h3>{% endifchanged %}

    <li> {{ forloop.counter }} {{entrada.user}}<a href="{{entrada.get_absolute_url }}">
{{ entrada }}</a></li>
{% endfor %}
</ul>

{% endblock %}

Django_GestionesCasasVersion1_11/polls/templates/polls/iframe.html
{% if xats %}
	{% for xat in xats %}
		<p>[{{xat.date_sent}}] {{xat.user}}: {{xat.text}}</p>
	{% endfor %}
{% endif %}

Django_GestionesCasasVersion1_11/polls/templates/polls/search.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>Search{% if query %} Results{% endif %}</title>
</head>
<body>
  <h1>Search</h1>
  <form action="." method="GET">
    <label for="q">Search: </label>
    <input type="text" name="q" value="{{ query|escape }}">
    <input type="submit" value="Search">
  </form>
 
  {% if query %}
    <h2>Results for "{{ query|escape }}":</h2>
    {% if results %}
      <ul>
      {% for xats_any in results %}
        <li>[{{ xats_any.dateField }}] {{ xats_any.user }}: {{ xats_any.message|escape }}</li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No xats found</p>
    {% endif %}
  {% endif %}


</body>
</html>

Django_GestionesCasasVersion1_11/polls/templates/polls/user_detail.html
<html>
<head>
	<title>User Detail</title>
</head>
<body>
	<h1>Nom d'usuari: {{ user.username }}</h1>
	<h2>Historial de missatges</h2>
	{% for xat in user.xat_set.all %}
		[{{ xat.date_sent }}] {{ xat.user }}: {{ xat.text }}<br>
	{% endfor %}
</body>
</html>

Django_GestionesCasasVersion1_11/polls/templates/polls/users.html
{% extends "polls/base.html" %}
{% block title %} Contactes {% endblock %}
{% block content %}
<h1>Contactes</h1>

{% if latest_users_list %}
		{% for user in latest_users_list %}
    		<li><a href="{% url 'polls:user_detail' user.id %}">-{{ user.username }} </a></li> <br>
    	{% endfor %}
{% endif %}	
{% endblock %}

Django_GestionesCasasVersion1_11/polls/templates/polls/xat.html
{% extends "polls/base.html" %}
{% block title %}Xats{% endblock %}
{% block h1 %}Xats{% endblock %}
{% block content %}
	
	<h2>Historial de Xats</h2>
	
	{% if xats %}
		{% for xat in xats %}
			<li>[{{ xat.date_sent }}] {{ xat.user }}: {{ xat.text }} </li><br>
		{% endfor %}
	{% endif %}
{% endblock %}
{% block aside %}
	{% if user.is_authenticated %}
		&nbsp;<a href="{% url 'polls:users' %}">Contactes</a>
		<form action="{% url 'polls:xat' %}" method="post">{% csrf_token %}
		<iframe src="{% url 'polls:iframe' %}"></iframe>
		{{ form.as_p }}
		<input type="submit" value="Submit" />
		</form>
	{% endif %}
	
{% endblock %}
{% block navinf %}
	<a href="/polls/xats/{{year}}">Xats d'enguany</a>&nbsp|&nbsp
	<a href="/polls/xats/{{year}}/{{month}}">Xats d'aquest mes</a>
	&nbsp|&nbsp
	<a href="{% url 'search' %}">Consulta xats per data</a>
{% endblock %}